### ISSUE TITLE
Being able to pass the -allowUntrusted flag to installer would be pretty helpful for older packages.

### ISSUE THREAD

**Issue by DaveCasey** [chef-cookbooks/dmg#31]
Use case: Supermarket Xcode cookbook could also support Lion if it could pass -allowUntrusted to dmg_package when installing the aging command line tools package.

Thanks,
-Dave

**Comment by Elias-from-Testfabrik** [comment]
Yeah, such a change would be greatly appreciated and probably very simple to do.

If you need an example piece of code, try installing the Java 8 JDK on a Mac that does not accept the certificate by default, the example below is from a 10.8 machine:
_---- Begin output of sudo installer -pkg '/Volumes/JDK 8 Update 92/JDK 8 Update 92.pkg' -target / ----
STDOUT: installer: Package name is JDK 8 Update 92
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
---- End output of sudo installer -pkg '/Volumes/JDK 8 Update 92/JDK 8 Update 92.pkg' -target / ----_

**Comment by tas50** [comment]
This has been fixed in 4.1 thanks to @melissafritcher
