### ISSUE TITLE
How to install a .pkg file from a URL with this LWRP?

### ISSUE THREAD

**Issue by dtenenba** [chef-cookbooks/dmg#34]
Not a bug but a question.
Using the dmg LWRP, How do I install a .pkg file from a URL onto a Mac OS X node WITHOUT using brew or port?

Your README says:

"Optionally, the LWRP can install an "mpkg" or "pkg" package using installer(8)."

But there's no documentation that I could find on how to do this.
I tried, for example:

```
dmg_package "MacTex" do
  source 'http://tug.org/cgi-bin/mactex-download/MacTeX.pkg'
end
```

That gives me an error saying 'brew' was not found. I don't want to use brew or port.

I could of course call 'installer' in an 'execute' resource but I was hoping for something more idempotent and chef-like. You tantalizingly suggest that this is possible with the dmg package.

Thanks.

**Comment by cheeseplus** [comment]
The cookbook only supports install an mpkg or pkg _from_ a DMG.
