### ISSUE TITLE
Feature Request: add support for XIP files

### ISSUE THREAD

**Issue by jerroydmoore** [chef-cookbooks/dmg#38]
### Cookbook version
3.1.0

### Chef-client version
Chef Development Kit Version: 0.17.17
chef-client version: 12.13.37
delivery version: master (f68e5c5804cd7d8a76c69b926fbb261e1070751b)
berks version: 4.3.5
kitchen version: 1.11.1

### Platform Details
El Capitan

### Scenario:
Trying to install xcode 8. Starting with xcode 8, apple switched from distributing xcode from a DMG file to a XIP file, to address the xcode shadow vulnerability. Note: Only XIP files from Apple are valid.

### Steps to Reproduce:
NA

### Expected Result:
NA

### Actual Result:
NA

**Comment by jerroydmoore** [comment]
This feature request may be inappropriate for the dmg cookbook, but the conversation has to start somewhere. Maybe an appropriate solution is to create a xip cookbook with a resource provider, but it would be better if our cookbooks didn't need to manually detect xip vs dmg.

**Comment by tas50** [comment]
This is probably something we should do in a new xip cookbook since it's a totally different thing.
